# Generated by Django 2.1.2 on 2018-11-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_num', models.CharField(max_length=10)),
                ('data_file', models.FileField(null=True, upload_to='')),
                ('ml_result', models.CharField(max_length=50)),
            ],
        ),
    ]
