# Generated by Django 2.1.2 on 2018-11-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hexagon',
            name='member_num',
        ),
        migrations.RemoveField(
            model_name='hexagon',
            name='ml_result',
        ),
    ]
